const WORDLE_CONSTANTS = {
    MAX_COL: 5,
    MAX_ROW: 6,
    MAX_LEVEL: 5,
    FLIP_DELAY: 400,
    UPDATE_SCORE_DELAY: 100,
    WIN_ANIMATION_DELAY: 2400,
    WIN_HIGHLIGHT_DELAY:200,
    LEVEL_SCORE: 1000,
    ROW_REMAINING_SCORE: 100,
    ERROR_SHAKE_DURATION: 500,
  };
  
  export default WORDLE_CONSTANTS;
  